//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goldlight.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goldlight.Contracts.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array must not be empty..
        /// </summary>
        internal static string ArrayMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArrayMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection must not be empty..
        /// </summary>
        internal static string CollectionMustNotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date {0} must not be earlier than {1}..
        /// </summary>
        internal static string DateCannotBeEarlierThan {
            get {
                return ResourceManager.GetString("DateCannotBeEarlierThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date {0} must not be greater than {1}..
        /// </summary>
        internal static string DateCannotBeGreaterThan {
            get {
                return ResourceManager.GetString("DateCannotBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Guid must be empty..
        /// </summary>
        internal static string GuidMustBeEmpty {
            get {
                return ResourceManager.GetString("GuidMustBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Guid must not be empty..
        /// </summary>
        internal static string GuidMustNotBeEmpty {
            get {
                return ResourceManager.GetString("GuidMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text for contains cannot be null or whitespace..
        /// </summary>
        internal static string NullOrWhiteSpaceContains {
            get {
                return ResourceManager.GetString("NullOrWhiteSpaceContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ends with cannot be null or whitespace..
        /// </summary>
        internal static string NullOrWhiteSpaceEndsWith {
            get {
                return ResourceManager.GetString("NullOrWhiteSpaceEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message cannot be null or whitespace..
        /// </summary>
        internal static string NullOrWhiteSpaceMessage {
            get {
                return ResourceManager.GetString("NullOrWhiteSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be null or whitespace..
        /// </summary>
        internal static string NullOrWhiteSpaceName {
            get {
                return ResourceManager.GetString("NullOrWhiteSpaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starts with cannot be null or whitespace..
        /// </summary>
        internal static string NullOrWhiteSpaceStartsWith {
            get {
                return ResourceManager.GetString("NullOrWhiteSpaceStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must contain..
        /// </summary>
        internal static string StringMustContain {
            get {
                return ResourceManager.GetString("StringMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must end with..
        /// </summary>
        internal static string StringMustEndWith {
            get {
                return ResourceManager.GetString("StringMustEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string cannot be null or empty..
        /// </summary>
        internal static string StringMustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringMustNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string cannot be null or a whitespace..
        /// </summary>
        internal static string StringMustNotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringMustNotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must not contain this text..
        /// </summary>
        internal static string StringMustNotContain {
            get {
                return ResourceManager.GetString("StringMustNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must not end with this text..
        /// </summary>
        internal static string StringMustNotEndWith {
            get {
                return ResourceManager.GetString("StringMustNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must not start with this text..
        /// </summary>
        internal static string StringMustNotStartWith {
            get {
                return ResourceManager.GetString("StringMustNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must start with this text..
        /// </summary>
        internal static string StringMustStartWith {
            get {
                return ResourceManager.GetString("StringMustStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The types are cannot be cast..
        /// </summary>
        internal static string UnableToCast {
            get {
                return ResourceManager.GetString("UnableToCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be the default..
        /// </summary>
        internal static string ValueMustNotBeDefault {
            get {
                return ResourceManager.GetString("ValueMustNotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be null..
        /// </summary>
        internal static string ValueMustNotBeNull {
            get {
                return ResourceManager.GetString("ValueMustNotBeNull", resourceCulture);
            }
        }
    }
}
